# netlify.toml

[build]
  command = "npm run build"
  functions = "dist/.netlify/functions"
  publish = "public"

[build.environment]
  NODE_VERSION = "20.12.2"

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# Configurações para deploy local com Netlify CLI (mantendo como antes)
[dev]
  framework = "#custom"
  command = "yarn dev"
  targetPort = 3000
  publish = "dist"
  functions = "dist/.netlify/functions" # Ajustei para ser consistente com o build